version: "3.9"
services:
  db:
    image: 'postgres:14'
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    restart: always
  api:
    build:
      context: '../api'
      dockerfile: '../api/Dockerfile'
    container_name: "api"
    environment:
      API_PORT: ${API_PORT}
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${API_FRONTEND_URL}
      SECRET_KEY: ${API_SECRET_KEY}
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - db
    restart: always
  frontend:
    build:
      context: '../frontend'
      dockerfile: '../frontend/Dockerfile'
    container_name: "frontend"
    environment:
      API_URL: ${API_URL}
    ports:
      - '80:80'
    depends_on:
      - api
    restart: always

volumes:
  db-data: